version: "3.8"

services:
  app:
    build:
      context: .
    container_name: devops-takehome
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      RUST_LOG: debug
